### ISSUE TITLE
data.baseUrl returns the wrong protocol for secure sites.

### ISSUE THREAD

**Issue by arti5m** [apostrophecms/apostrophe#1205] opened 2018-01-22 19:37 UTC
https://github.com/apostrophecms/apostrophe/blob/1812b9b5b1fe69077a3b9c75e9d0d3e289dc1c05/lib/modules/apostrophe-express/index.js#L604

**Comment by boutell** [comment] 2018-01-22 19:38
You can address this by setting `baseUrl` correctly in `data/local.js`, and you always would for a production site (right?), but we should look at whether we can configure Express to trust the proxy and thus know it is secure.

**Comment by arti5m** [comment] 2018-01-22 19:50
This sort of thing? 
https://github.com/techgaun/til/blob/master/nodejs/nodejs-req-protocol-with-nginx-proxy.md

**Comment by timashev** [comment] 2018-01-25 02:31
Kind of duplicate of this: https://github.com/apostrophecms/apostrophe-workflow/issues/126

**Comment by boutell** [comment] 2020-01-02 20:12
Going to close this because there is a working solution based on configuring baseUrl and there has been no movement.

**Closed by boutell** 2020-01-02 20:12 UTC
Labels: bug
